/** @type {import('tailwindcss').Config} */
export default {
  content: [
    
    "./src/OrderAndProductionUi/OrderAndProduction.jsx",
    "./src/OrderManagement/order.jsx",
     "./src/OrderManagement/orderRet.jsx",
     "./src/ProductionManagement/productionPlaning.jsx",
     "./src/ProductionManagement/ResourcesPlaning.jsx",
     "./src/ProductionManagement/productionCost.jsx",
     "./src/ProductionManagement/ProductionRet.jsx",
     "./src/ProductionManagement/ResourceRet.js",
     "./src/OrderAndProductionUi/AboutUs.jsx",
     "./src/OrderandProductionReport/OrderandProductionReport.jsx",
     "./src/financehandling/financeuserinterface.jsx",
     "./src/Shared/Header.jsx",
     "./src/Shared/Footer.jsx",
     "./src/Home/Home.jsx",
     "./src/financehandling/salarycalculateinterface.jsx",
     "./src/financehandling/vieworderinvoice.jsx",
     "./src/financehandling/billorderret.jsx",
     "./src/financehandling/fiMainTable.jsx",
     "./src/AboutUS/AboutUs.jsx",
     "./src/financehandling/orderbillinterface.jsx",
     "./src/financehandling/salaryret.jsx",
     "./src/financehandling/salaryupdate.jsx",
     "./src/AddEmp/Addemp.jsx",
    "./src/leaveReqForm/LeaveForm.jsx",
    "./src/SalaryMangment/Salarymang.jsx",
    "./src/AttendanceT/Attencance.jsx",
    "./src/AddEmpRet/empRet.jsx",
    "./src/AddEmp/Addemp.jsx",
    "./src/leaveReqForm/LeaveForm.jsx",
    "./src/SalaryMangment/Salarymang.jsx",
    "./src/AttendanceT/Attencance.jsx",
    "./src/AddEmpRet/empRet.jsx",

  ],
  theme: {
    extend: {},
  },
  plugins: [],
}